spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/raven_db
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    generate-ddl: false
  messages:
    basename: messages

server:
  error:
    include-message: always
  port: 8080
  servlet:
    context-path: /api
